#!/bin/bash

mkdir -p ~/.vim/bundle
cd ~/vim/
cp vimrc  ~/.vimrc
git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
cd 
rm -rf ~/vim
cd .vim
mkdir colors
git clone https://github.com/tomasr/molokai
mv molokai/colors/molokai.vim ~/.vim/colors/
vim .vimrc
